languageCode = "en-US"
layoutdir = "layouts"
publishdir = "public"
baseurl = "/"
googleAnalytics = ""
theme = "hugo-vitae"

[params]
  author = "Rajesh Manghani"
  title = "Rajesh Manghani's Resume"
  description = "Dwai Banerjee's Resume"
  avatar = "Rajesh_Manghani.jpg"
  #email = "mail Dwai / "
  email_full = "mailto:rajesh.manghanii@gmail.com"
  #website = "Resume pdf download"
  github = "Manghani-Rajesh"
  linkedin = "rajesh-manghani-1044ab50"
  #tel = "+44 0000 000000"
  #tel_full = "+440000000000"
  #google_maps = "https://www.google.com/maps/place/Manyata+Tech+Park"
  #address = "44 Perth Street"
  #postcode = "EH3 5BL"
  city = "Bangalore"
  country = "India"

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  
[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5
